### ISSUE TITLE
Insufficient documentation for migrating VMs on k8s via CLI

### ISSUE THREAD

**Issue by tanaypatankar** [konveyor/forklift-operator#242]
I've referred the docs present in https://github.com/konveyor/forklift-operator/blob/main/docs/k8s.md, and https://forklift-docs.konveyor.io/documentation/doc-Migration_Toolkit_for_Virtualization/master/index.html#migrating-virtual-machines-from-cli. 

The correct pods are not brought up and there is no k8s specific detailed guide.

**Comment by fbladilo** [comment]
@tanaypatankar The scope of https://github.com/konveyor/forklift-operator/blob/main/docs/k8s.md is limited to install Forklift on k8s but it is not an official Forklift documentation regarding migrations VMs on k8s with CLI, I believe this issue is a better fit for Forklift Documentation repo :

https://github.com/konveyor/forklift-documentation 

With that said, if the OLM installation is failing with k8s.md instructions then we can troubleshoot here.

**Comment by tanaypatankar** [comment]
@fbladilo You are correct, I'll shift it to the correct repo. OLM installation does go through, but could you clarify what pods are brought up after following k8s.md? I observe only one pod.
`NAME                      READY   STATUS    RESTARTS   AGE
konveyor-forklift-k88r5   1/1     Running   0          16h`

**Comment by tanaypatankar** [comment]
Hi, sorry for the late response. I completely missed the 1.23 min requirement, so no point in continuing this issue at the moment. Will reopen if I'm unable to get the correct pods up after upgrading. Thanks for your help @fbladilo!
